// TODO: cleanup the generated code not to throw hundreds of these warnings
#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(non_camel_case_types)]

extern crate inflector;
extern crate lv2_raw;
extern crate libc;
// #[macro_use]
// extern crate rome;

pub mod core;
pub mod myutils;
pub mod ui;
pub mod port;
pub mod ttl;
//mod ontology;

pub use libc::strcmp; // needed for the code generated by the `plugin_ui` macro

pub use core::*;
pub use myutils::*;
pub use ui::PluginUI;

pub use lv2_raw::core::{LV2Handle, LV2Descriptor, LV2Feature};
pub use lv2_raw::ui::{LV2UIDescriptor, LV2UIIdleInterface, LV2UIShowInterface, LV2UIHandle};
